### ISSUE TITLE
Task completion callback has inconsistent payloads

### ISSUE THREAD

**Issue by guidowb** [cloudfoundry-incubator/bbs#3]
I'm creating a task with a completion callback through the receptor. If my callback server is up at the time of task completion, I get only a minimal payload:
```
{"task_guid":"2f9c835e-3700-49f4-809b-05819ea462e5","failed":false,"failure_reason":"","result":""}
```

Ironically, if my callback server is down at the time of task completion, and comes up while the task is still in resolving state, I end up getting a complete payload:
```
{"action":{"run":{"path":"ruby","args":["/app/app.rb","1"],"dir":"/app","resource_limits":{},"user":"vcap"}},"completion_callback_url":"http://guidowenbergmbp:8080/tasks/complete","cpu_weight":0,"disk_mb":0,"domain":"task-manager-4d3a30d3-067d-4afd-8fec-5344b80c0117","log_guid":"","log_source":"","metrics_guid":"","memory_mb":0,"result_file":"","task_guid":"2355eb2b-2e54-4d8f-9a8f-dce07e8d45f3","rootfs":"docker:///cdavisafc/sleepd5","privileged":false,"cell_id":"","created_at":1445006597378868367,"failed":false,"failure_reason":"","result":"","state":"COMPLETED"}
```

According to the [receptor API documentation] (https://github.com/cloudfoundry-incubator/receptor/blob/master/doc/tasks.md#retrieving-tasks), the latter behavior is correct. But I'm only seeing it in the exception case, not in the normal case.

(filing this issue against bbs because that's where the callbacks come from)

**Comment by ematpl** [comment]
Hi, @guidowb,

Thanks for the report! The Diego team will investigate the discrepancy and figure out what's going on. I agree that it would be best for us to be consistent in the payload either way.

Best,
Eric

**Comment by cwlbraa** [comment]
Hi @guidowb,

What version of diego are you running?

**Comment by guidowb** [comment]
ltc version v0.5.0 (diego 0.1424.1)
now updating to the latest and will try again

**Comment by cwlbraa** [comment]
As of 1434 (and quite a few releases before) the TaskCallbackResponse sent by the bbs should be very close to what you're seeing in the normal case. However, it's possible that certain versions of the receptor will try to send their own responses (as prior to introducing the bbs the receptor was responsible for sending that response,) and were a receptor to send the response, it might send the unabbreviated version.

**Comment by guidowb** [comment]
re-tested this with ltc version v0.6.0-34-g32acfa9 (diego 0.1434.0)

The good news is that I'm no longer seeing the inconsistency. The bad news is that I'm now consistently getting the abbreviated response, which is in conflict with the above-referenced documentation. The doc specifically says:

```
In both cases, you will receive an object that includes all the fields on the TaskCreateRequest
and the following additional fields:

{
    ... all TaskCreateRequest fields...

    "state": "RUNNING",

    "cell_id": "cell-identifier",

    "failed": true/false,
    "failure_reason": "why it failed",
    "result": "the contents of result_file",
}
```

I could **mostly**  live with the abbreviated form, except that I'd really like to be able to know what cell it ran on. If I'm not polling during the RUNNING state, that information is gone once I get the completion callback.

**Comment by jfmyers9** [comment]
Hi @guidowb,

May I ask why you would like to know which cell your task has run on? To me that seems like somewhat of an internal implementation detail that ideally would no matter to the end user.

As it stands, when we complete a Task, we remove the information about which cell it was running on from our internal backing store, and thus when we post to the task call back url, we no longer have the information above.

Also, as of [diego release v0.1432.0](http://bosh.io/releases/github.com/cloudfoundry-incubator/diego-release?version=0.1432.0), the receptor is no longer a maintained by the Diego team. Instead, the Lattice team now maintains the state of the receptor, therefore any documentation in the repository is not guaranteed to remain in sync with current final releases of Diego. It may be worth having a conversation with @davidwadden, or opening up an issue on the receptor itself to address these concerns. 

Best,

@jfmyers9, CF Diego Team

**Comment by guidowb** [comment]
Hi @jfmyers9,

Totally fair question. My desire for this info is because I'm trying to convince a partner that they should execute their batch/scheduled jobs on Cloud Foundry, and leave the distribution of tasks across cells to us. I had a little prototype that submitted tasks and visualized where they were run. That breaks on 1434.

I do agree that these are internal details, and if that's the rationale for abbreviating the payload I can live with it. There are other ways for me to achieve what I need.

Yes, I know that the receptor is now Lattice only, but I'm trying to establish requirements for a task API provided by the cloud controller to access the same Diego functionality in CF. It's the core task support that I really care about, not the Receptor front-end to it.

Guido.

**Comment by ematpl** [comment]
Hi, @guidowb,

Thanks for the extra context! Would it instead be helpful to have a stream of Task events available on the receptor or BBS API?

Best,
Eric

**Comment by guidowb** [comment]
@ematpl Yes!  :+1: That's exactly what I want!

**Comment by ematpl** [comment]
Great, I've generated https://www.pivotaltracker.com/story/show/107732540 for adding task events to the BBS event stream. Once that's present, the receptor would need to handle the task events as well.

Since later Diego versions provide consistent payloads, and since I've captured that feature request in the linked story, I'll close this issue out. Thanks again!
